/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bytebankers.swing.ui;

import com.bytebankers.contabancaria.ex.ValorTransacionalInvalido;
import com.bytebankers.contabancaria.model.ContaBanco;
import com.bytebankers.contabancaria.service.ContaBancoService;
import com.bytebankers.swing.http.ClienteHttp;
import com.bytebankers.swing.ui.telas_mensagem.ErroTransacaoNegada;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author sammy
 */
public class TelaTransacao extends javax.swing.JFrame {
    
    private ContaBanco conta;
    private String transacoes[] = {"Digite o valor do depósito", "Digite o valor do saque", "Digite o valor da mensalidade"};
    private String transacao[] = {"Depositar", "Sacar", "Pagar Mensalidade"};
    private int escolha;

    /**
     * Creates new form Depositar
     */
    public TelaTransacao(ContaBanco conta, int n) {
        this.conta = conta;
        this.escolha = n;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        textoTransacao = new javax.swing.JLabel();
        valorTransacao = new javax.swing.JTextField();
        efeturaTransacao = new javax.swing.JButton();
        currency = new javax.swing.JLabel();
        valorSaldo = new javax.swing.JLabel();
        efeturaTransacao1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoTransacao.setText(transacoes[escolha]);

        valorTransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTransacaoActionPerformed(evt);
            }
        });

        efeturaTransacao.setText(transacao[escolha]);
        efeturaTransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efeturaTransacaoActionPerformed(evt);
            }
        });

        currency.setText("R$");

        valorSaldo.setText("Saldo atual : " + this.conta.getSaldo());

        efeturaTransacao1.setText("Voltar");
        efeturaTransacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(currency)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(efeturaTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(textoTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(efeturaTransacao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(textoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency))
                .addGap(26, 26, 26)
                .addComponent(efeturaTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(efeturaTransacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valorSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void valorTransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTransacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTransacaoActionPerformed

    private void efeturaTransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efeturaTransacaoActionPerformed
        ContaBanco contaN = this.conta;
        boolean ocorreuErro = false;
        if(escolha == 0){
            try{
                contaN.depositar(Float.parseFloat(valorTransacao.getText()));
                contaN = ClienteHttp.salvarAlteracoes(conta);
            }catch(ValorTransacionalInvalido e){
                ocorreuErro = true;
            }
        }else if(escolha == 1){
            try{
                System.out.println(this.conta.getSaldo() - Float.parseFloat(valorTransacao.getText()));
                contaN.sacar(Float.parseFloat(valorTransacao.getText()));
            }catch(ValorTransacionalInvalido e){
                ocorreuErro = true;
            }
            contaN = ClienteHttp.salvarAlteracoes(conta);
        }else{
            try{
                contaN.pagarMensalidade(Float.parseFloat(valorTransacao.getText()));
                contaN = ClienteHttp.salvarAlteracoes(conta);
            }catch(ValorTransacionalInvalido e){
                ocorreuErro = true;
            }
        }
        if(ocorreuErro){
            this.dispose();
            new ErroTransacaoNegada(this.conta).setVisible(true);
        }else{
            this.dispose();
            new TelaPrincipal(contaN).setVisible(true);
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_efeturaTransacaoActionPerformed

    private void voltar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal(this.conta).setVisible(true);
    }//GEN-LAST:event_voltar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaTransacao().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currency;
    private javax.swing.JButton efeturaTransacao;
    private javax.swing.JButton efeturaTransacao1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel textoTransacao;
    private javax.swing.JLabel valorSaldo;
    private javax.swing.JTextField valorTransacao;
    // End of variables declaration//GEN-END:variables
}
